/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.View;

/**
 *
 * @author Desenvolvedor
 */
public class FrMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrMenuPrincipal
     */
    public FrMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();
        menusPrincipais = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuItemDentistas = new javax.swing.JMenuItem();
        menuItemClientes = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuFerramentas = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrame1.setTitle("Menu de Acesso Rápido");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel2.setText("Sistema de Gerenciamento de:");
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 210, 14);
        jInternalFrame1.getContentPane().add(jButton1);
        jButton1.setBounds(170, 30, 70, 60);
        jInternalFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(10, 30, 70, 60);
        jInternalFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(90, 30, 70, 60);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 150, 490, 180);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/wallpaper_Escova.jpg"))); // NOI18N
        getContentPane().add(wallpaper);
        wallpaper.setBounds(0, 0, 500, 330);

        menuCadastro.setText("Cadastro");

        menuItemDentistas.setText("Dentistas");
        menuItemDentistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDentistasActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemDentistas);

        menuItemClientes.setText("Clientes");
        menuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientesActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemClientes);

        menusPrincipais.add(menuCadastro);

        menuRelatorio.setText("Relatórios");
        menusPrincipais.add(menuRelatorio);

        menuFerramentas.setText("Ferramentas");
        menusPrincipais.add(menuFerramentas);

        menuSair.setText("Sair");
        menusPrincipais.add(menuSair);

        setJMenuBar(menusPrincipais);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemDentistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDentistasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemDentistasActionPerformed

    private void menuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenuItem menuItemClientes;
    private javax.swing.JMenuItem menuItemDentistas;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuBar menusPrincipais;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
